FROM adoptopenjdk/openjdk11
ARG DEPANDENCY=target/dependency
COPY ${DEPANDENCY}/BOOT-INF/lib app/lib
COPY ${DEPANDENCY}/META-INF app/META-INF
COPY ${DEPANDENCY}/BOOT-INF/classes app
ENTRYPOINT ["java","-cp","app:app/lib/*","com.pp.sun.DockerImage1.DockerImage1Application"]
