apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec: 
  containers:
  - name: liveness-pod
    image: ubuntu
    tty: true
    livenessProbe:
      exec:
        command:
        - service
        - nginx
        - status
      initialDelaySeconds: 20
      periodSeconds: 5