apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
spec: 
  containers:
  - name: readiness-pod
    image: ubuntu
    tty: true
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5