apiVersion: apps/v1
kind: Deployment
metadata: 
  name: prasun-tolerations-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      tire: frountend
  template:
    metadata:
      labels:
        tire: frountend
    spec:
      containers:
      - name: nginx-container
        image: nginx
      tolerations:
      - key: key
        operator: Exists
        effect: NoSchedule